feat: add pie graph
datadeque/platform pull request #25
Opened 2022-03-24 15:10 UTC by jodijang

2022-03-24 15:10 UTC, jodijang commented on src/components/EditGraphPanel/EditGraphPanel.tsx
> +  legend?: string
made legend optional since pie graphs use ids as the legend

2022-03-24 15:11 UTC, jodijang commented on src/components/EditGraphPanel/EditGraphPanel.tsx
> +  handleLegendChange?: (e: ChangeEvent<HTMLInputElement>) => void
made legend change function optional for the same reason

2022-03-24 20:46 UTC, H-Richard commented on src/components/PieGraphNode/PieGraphNode.module.scss
> +  width: 100%;
should fill parent

2022-03-24 20:46 UTC, H-Richard commented on src/components/PieGraphNode/PieGraphNode.tsx
> +            ]}
move to another file

2022-03-25 14:05 UTC, H-Richard requested changes

2022-03-25 14:05 UTC, H-Richard commented on src/components/EditGraphPanel/EditGraphPanel.tsx
> +                    console.log(data[id])
remove `console.log`

2022-03-25 14:05 UTC, H-Richard commented on src/components/EditGraphPanel/EditGraphPanel.tsx
> +              <IconButton
perhaps we should disable the button when `newValue` is undefined

2022-03-25 15:58 UTC, H-Richard approved these changes

2022-03-25 16:01 UTC, merged